//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicProject.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicProject.Service.Resources.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar usuário..
        /// </summary>
        public static string User_Error_Create {
            get {
                return ResourceManager.GetString("User_Error_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao alterar usuário..
        /// </summary>
        public static string User_Error_Delete {
            get {
                return ResourceManager.GetString("User_Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro listar usuários..
        /// </summary>
        public static string User_Error_List {
            get {
                return ResourceManager.GetString("User_Error_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao buscar usuário..
        /// </summary>
        public static string User_Error_Search {
            get {
                return ResourceManager.GetString("User_Error_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar usuário..
        /// </summary>
        public static string User_Error_Update {
            get {
                return ResourceManager.GetString("User_Error_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário adicionado com sucesso..
        /// </summary>
        public static string User_Success_Create {
            get {
                return ResourceManager.GetString("User_Success_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário excluído com sucesso..
        /// </summary>
        public static string User_Success_Delete {
            get {
                return ResourceManager.GetString("User_Success_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busca de usuários realizada com sucesso..
        /// </summary>
        public static string User_Success_List {
            get {
                return ResourceManager.GetString("User_Success_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busca de usuário realizada com sucesso..
        /// </summary>
        public static string User_Success_Search {
            get {
                return ResourceManager.GetString("User_Success_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário atualizado com sucesso..
        /// </summary>
        public static string User_Success_Update {
            get {
                return ResourceManager.GetString("User_Success_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email do usuário não pode ser vazio..
        /// </summary>
        public static string User_Validate_Email {
            get {
                return ResourceManager.GetString("User_Validate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inválido..
        /// </summary>
        public static string User_Validate_Invalid {
            get {
                return ResourceManager.GetString("User_Validate_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação de usuário administrativo não pode ser vasio..
        /// </summary>
        public static string User_Validate_IsAdmin {
            get {
                return ResourceManager.GetString("User_Validate_IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do usuário não pode ser vazio..
        /// </summary>
        public static string User_Validate_Name {
            get {
                return ResourceManager.GetString("User_Validate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string User_Validate_Not_Found {
            get {
                return ResourceManager.GetString("User_Validate_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha do usuário não pode ser vazio.
        /// </summary>
        public static string User_Validate_Password {
            get {
                return ResourceManager.GetString("User_Validate_Password", resourceCulture);
            }
        }
    }
}
