// <auto-generated />
using System;
using BasicProject.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasicProject.Infra.Migrations
{
    [DbContext(typeof(BasicProjectContext))]
    [Migration("20190605161937_Task_User_Add_Password")]
    partial class Task_User_Add_Password
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasicProject.Infra.Entity.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Active");

                    b.Property<string>("City");

                    b.Property<string>("Complement");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("Number");

                    b.Property<string>("Street");

                    b.Property<DateTimeOffset?>("UpdateDate");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("BasicProject.Infra.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Active");

                    b.Property<DateTimeOffset>("CreationDate");

                    b.Property<string>("Email");

                    b.Property<int>("Gender");

                    b.Property<string>("IdSocial");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<DateTimeOffset?>("UpdateDate");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BasicProject.Infra.Entity.Address", b =>
                {
                    b.HasOne("BasicProject.Infra.Entity.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("BasicProject.Infra.Entity.Address", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
